### ISSUE TITLE
Support sysctl / kernel params configuration

### ISSUE THREAD

**Issue by n4ss** [moby/libentitlement#35]
There is a need for `sysctl` support for Docker Swarm Mode: https://github.com/moby/moby/issues/25209

We should probably add the ability for people to specify kernel/sysctl parameters to run the image with.

**Comment by raarts** [comment]
I would like to see the `sysctls` from docker-compose supported in stack deploy too. Redis for example needs `/proc/sys/net/core/somaxconn`, and since that's namespaced, setting it on the docker host has no effect.

**Comment by mattsp1290** [comment]
+1

**Comment by delissonjunio** [comment]
Any news on this? Just finished setting up a docker-compose workflow just to find out my swarm won't be running it any soon, as I need to set some sysctls/ulimits for the containers

**Comment by raarts** [comment]
Any progress on this? I can't help but noticing that commits to this repo have stopped three months ago.

**Comment by 13428282016** [comment]
*no swearing*

**Comment by raarts** [comment]
Yes, so why am i defending docker swarm in HN?

**Comment by n4ss** [comment]
There are currently higher priorities on my side at the moment.

But this is an open-source project, feel free to send a PR if this is something that has high priority to you, I'd gladly review it and merge :)

**Comment by thaJeztah** [comment]
WIP Pull request for setting sysctl for swarm services: https://github.com/moby/moby/pull/37701 /  https://github.com/docker/swarmkit/pull/2729

**Comment by marzlarz** [comment]
How close are we to getting the above pull request merged? It feels like we have been asking for sysctl setting modification for Docker Services for quite some time now... forced to run standalone containers until this is ready.
