### ISSUE TITLE
handling mutually exclusive entitlements

### ISSUE THREAD

**Issue by tych0** [moby/libentitlement#42]
Can we make `host.devices.admin` and `security.view` mutually exclusive somehow, since one of them explicitly allows and the other explicitly denies CAP_SYS_ADMIN? There is probably some overlap with syscalls too.

I guess the implementation bits about this are perhaps remembering if a capability came from a particular entitlement, or if it came from the default profile supplied. But it seems like in the above case, if someone has specified both, they would want to know that they're really not going to get `host.devices.admin` if they list `security.view` second.

**Comment by n4ss** [comment]
What I was thinking for this was to have an "inheritance" system, with hidden private entitlements which could be shared by top-level entitlements, like a "private.mount" which would give access to CAP_SYS_ADMIN and `mount`. Both `host.devices.admin` and `security.view` would enable it, that way you'd be able to verify if it's already in a permission set.
