### ISSUE TITLE
should not have multiple potentially conflicting entitlements

### ISSUE THREAD

**Issue by justincormack** [moby/libentitlement#68]
Currently, for example, network access is defined as

`network.none`, `network.user`, `network.proxy`, `network.admin`

This is quite non standard. The Apple way is that there is an entitlement called `network` which if unset gives you no network - "Each entitlement has a default value, which in most cases disables the capability associated with the entitlement. When you set an entitlement, you are overriding the default by providing an appropriate key-value pair."

So the values should be defined as

`network=none` (default, same is if not provided)
`network=user`
`network=proxy`
`network=admin`

In that way you also do not have to deal with someone setting `network.none` and `network.admin` as this will no longer be possible.

This would also clear up a few more cases where it is not clear, eg `security.confined` is part of a group with `security.view`, while `security.read-only` is a boolean.

**Comment by n4ss** [comment]
very good idea! I'm implementing that right now but I just need to remove the constraints that any entitlement id needs to be scoped within it's entitlement domain as discussed.

Should we go for `network=none` or `network.access=none` ? (I don't want people to be confused and think about the `network` flag on docker CLI for example and as you mentioned, there might be other networky things to configure through it later on so the latter is probably better)
